services:
  postgres:
    image: postgres:15
    container_name: mission_control_db
    restart: always
    environment:
      POSTGRES_DB: mission_control_db
      POSTGRES_USER: mission_user
      POSTGRES_PASSWORD: mission_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  missioncontrolsystem:
    image: missioncontrolsystem
    build:
      context: .
      dockerfile: MissionControlSystem/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mission_control_db
      - DB_USER=mission_user
      - DB_PASSWORD=mission_user

volumes:
  postgres_data:

